import { useState, useEffect } from 'react';
import { FileText, Save, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import AdminLayout from '@/components/layouts/AdminLayout';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useQueryClient } from '@tanstack/react-query';

const AdminSettingsPaperTemplate = () => {
  const queryClient = useQueryClient();
  const [paperSchoolName, setPaperSchoolName] = useState('');
  const [paperInstructionsDaily, setPaperInstructionsDaily] = useState('');
  const [paperInstructionsFull, setPaperInstructionsFull] = useState('');
  const [paperFooter, setPaperFooter] = useState('');
  const [answerAccessFee, setAnswerAccessFee] = useState('2000');
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    (async () => {
      const { data } = await (supabase as any).from('site_settings').select('key, value');
      const m: Record<string, string> = {};
      data?.forEach((s: any) => { m[s.key] = s.value; });
      setPaperSchoolName(m['paper_template_school_name'] || 'AL Student');
      setPaperInstructionsDaily(m['paper_template_instructions_daily'] || '');
      setPaperInstructionsFull(m['paper_template_instructions_full'] || '');
      setPaperFooter(m['paper_template_footer'] || '');
      setAnswerAccessFee(m['answer_access_fee'] || '2000');
    })();
  }, []);

  const save = async () => {
    setIsSaving(true);
    try {
      const entries = [
        { key: 'paper_template_school_name', value: paperSchoolName },
        { key: 'paper_template_instructions_daily', value: paperInstructionsDaily },
        { key: 'paper_template_instructions_full', value: paperInstructionsFull },
        { key: 'paper_template_footer', value: paperFooter },
        { key: 'answer_access_fee', value: answerAccessFee },
      ];
      for (const e of entries) {
        const { error } = await (supabase as any).from('site_settings').upsert({ key: e.key, value: e.value, updated_at: new Date().toISOString() }, { onConflict: 'key' });
        if (error) throw error;
      }
      toast.success('Template settings saved!');
      queryClient.invalidateQueries({ queryKey: ['site-settings'] });
    } catch (err: any) { toast.error(err.message); }
    finally { setIsSaving(false); }
  };

  return (
    <AdminLayout>
      <div className="space-y-6 max-w-2xl">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2"><FileText className="w-6 h-6" /> Paper Template</h1>
          <p className="text-muted-foreground">Customize the header, instructions, and footer on generated papers</p>
        </div>
        <Card className="card-elevated">
          <CardContent className="pt-6 space-y-5">
            <div className="space-y-2">
              <Label>School / Institute Name (Header)</Label>
              <Input value={paperSchoolName} onChange={e => setPaperSchoolName(e.target.value)} placeholder="e.g. AL Student" />
              <p className="text-xs text-muted-foreground">Shown as the main title in the paper header</p>
            </div>
            <Separator />
            <div className="space-y-2">
              <Label>Instructions — Daily Paper</Label>
              <textarea
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-none"
                rows={3}
                value={paperInstructionsDaily}
                onChange={e => setPaperInstructionsDaily(e.target.value)}
                placeholder="Instructions printed on daily papers..."
              />
            </div>
            <div className="space-y-2">
              <Label>Instructions — Full Paper (50 MCQ + essays)</Label>
              <textarea
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-none"
                rows={3}
                value={paperInstructionsFull}
                onChange={e => setPaperInstructionsFull(e.target.value)}
                placeholder="Instructions printed on full papers..."
              />
            </div>
            <Separator />
            <div className="space-y-2">
              <Label>Footer Text</Label>
              <Input value={paperFooter} onChange={e => setPaperFooter(e.target.value)} placeholder="e.g. Generated by AL Student | www.alstudent.com" />
            </div>
            <Separator />
            <div className="space-y-2">
              <Label>Answer Access Fee (LKR) — One-time lifetime</Label>
              <Input type="number" value={answerAccessFee} onChange={e => setAnswerAccessFee(e.target.value)} placeholder="2000" />
              <p className="text-xs text-muted-foreground">Students without class enrollment pay this once for lifetime answer access</p>
            </div>
            <Button onClick={save} disabled={isSaving}>
              {isSaving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
              Save Template Settings
            </Button>
          </CardContent>
        </Card>
      </div>
    </AdminLayout>
  );
};

export default AdminSettingsPaperTemplate;
