
-- Generated papers table to store paper snapshots
CREATE TABLE public.generated_papers (
  id TEXT NOT NULL PRIMARY KEY,
  user_id UUID NOT NULL,
  grade INTEGER NOT NULL,
  paper_type TEXT NOT NULL DEFAULT 'DAILY',
  lesson_weights JSONB NOT NULL DEFAULT '[]',
  question_ids JSONB NOT NULL DEFAULT '[]',
  mcq_count INTEGER NOT NULL DEFAULT 0,
  short_essay_count INTEGER NOT NULL DEFAULT 0,
  essay_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.generated_papers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can create own generated papers"
  ON public.generated_papers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Anyone can view generated papers by ID"
  ON public.generated_papers FOR SELECT
  USING (true);

-- One-time answer access payments (lifetime unlock)
CREATE TABLE public.answer_access_payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE,
  payment_id UUID REFERENCES public.payments(id),
  status TEXT NOT NULL DEFAULT 'PENDING',
  granted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.answer_access_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own answer access payment"
  ON public.answer_access_payments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own answer access payment"
  ON public.answer_access_payments FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage answer access payments"
  ON public.answer_access_payments FOR ALL
  USING (is_admin_or_mod(auth.uid()));

-- Insert default site settings for paper template and answer access fee
INSERT INTO public.site_settings (key, value, description)
VALUES 
  ('paper_template_school_name', 'ICT Academy', 'School/institute name on generated papers'),
  ('paper_template_instructions_daily', 'Time Allowed: 30 minutes. Answer ALL MCQ questions. For essay questions, write clearly.', 'Instructions for daily papers'),
  ('paper_template_instructions_full', 'Time Allowed: 3 hours. Section A: Answer ALL MCQ questions. Section B: Answer ALL structured essay questions. Section C: Answer ALL essay questions.', 'Instructions for full papers'),
  ('paper_template_footer', 'Generated by ICT Academy | www.ictacademy.lk', 'Footer text on generated papers'),
  ('answer_access_fee', '2000', 'One-time fee (LKR) for lifetime answer access')
ON CONFLICT (key) DO NOTHING;
